---
format:
  revealjs: 
    theme: [default, slide-styles.scss]
    width: 1280
    height: 720
    include-after-body: 
      - "all-the-js-code.html"
echo: false
code-line-numbers: false
---

# Roundup

::: r-fit-text
We made it!
:::

## Your turn {.exercise}

*What is one thing you learned that surprised you?*

*What is one thing you learned that you plan to use?*

{{< countdown "5:00" >}}

## Resources to keep learning

. . .

- <https://quarto.org/>

. . .

- <https://github.com/quarto-dev/quarto-cli/discussions>

. . .

- <https://github.com/mcanouil/awesome-quarto>

. . .

## What we didn't get to

### Computations

Code blocks that use braces around the language name (e.g. ```` ```{r} ````) are executable, and will be run by Quarto during render.

```{{r}}
#| label: fig-airquality
#| fig-cap: "Temperature and ozone level."
#| warning: false

library(ggplot2)

ggplot(airquality, aes(Temp, Ozone)) + 
  geom_point() + 
  geom_smooth(method = "loess")
```

:::: footer
<https://quarto.org/docs/computations/r.html>
:::

## What we didn't get to

### Freeze

You can use the freeze option to denote that computational documents should never be re-rendered during a global project render, or alternatively only be re-rendered when their source file changes:

```yaml
execute:
  freeze: true  # never re-render during project render
```

```yaml
execute:
  freeze: auto  # re-render only when source changes
```

## Share what you have

- keep sharing in Discord, we learn better together

- Quarto Team Meetup, Tuesday 12:00 – 12:40pm

- The quarto team will be in the Lounge Wednesday morning

## Submit feedback before you leave

[pos.it/conf-workshop-survey](https://pos.it/conf-workshop-survey)

Your feedback is crucial! Data from the survey informs curriculum and format decisions for future conf workshops and we really appreciate you taking the time to provide it.
